default:
  image: node:20.10.0
  before_script:
    - corepack enable pnpm
    - pnpm config set store-dir .pnpm-store
    - pnpm i
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE !~ /\[skip ci\]/'

stages:
  - build-and-test
  - publish

build-and-test-job:
  stage: build-and-test
  script:
    - pnpm build
    - pnpm typecheck
    - NEXT_TEST_MODE=dev pnpm test -- -- --ci --runInBand
    - NEXT_TEST_MODE=start pnpm test -- -- --ci --runInBand

publish-job:
  stage: publish
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - pnpm build
    - pnpm typecheck
    - pnpm serwist-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && 
          $CI_PIPELINE_SOURCE != "merge_request_event" && 
          ($CI_COMMIT_TITLE =~ /chore\(packages\): publish packages/ || $CI_COMMIT_MESSAGE =~ /\[bump\]/)'
