name: Build examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build examples on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["16.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Cache .next
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/examples/*/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles(format('**/pnpm-lock.yaml')) }}-${{ hashFiles('examples/**.[jt]s', 'examples/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml')) }}-
      - name: Install dependencies
        run: pnpm install
      - name: Build apps
        run: pnpm examples:build
