name: Build examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build examples on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["16.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
        example:
          [
            minimal,
            next-9,
            lifecycle,
            cookie,
            cache-on-front-end-nav,
            custom-worker,
            custom-ts-worker,
            next-image,
            offline-fallback,
            offline-fallback-v2,
            web-push,
          ]
    if: ${{ github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            ${{ github.workspace }}/examples/${{ matrix.example }}/pnpm-lock.yaml
            ${{ github.workspace }}/examples/${{ matrix.example }}/.next/cache
      - name: Install dependencies for package
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Install dependencies for app
        run: pnpm link --dir examples/${{ matrix.example }}
      - name: Build app
        run: pnpm build
        working-directory: examples/${{ matrix.example }}
