name: Test & Publish package to npm
on: [push]
jobs:
  typecheck_lint_build:
    name: ⬣, 🔎, 🔨 Typecheck, lint, and build on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["16.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm turbo typecheck
      - name: Lint
        run: pnpm turbo lint
      - name: Build
        run: pnpm turbo build
  publish:
    name: 🚀 Release packages
    needs: [typecheck_lint_build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["16.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
    if: ${{ github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[bump ver]') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Create release PR
        uses: changesets/action@v1
        with:
          commit: "Update packages"
          title: "Update packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
