name: Test & Publish package to npm
on: [push]
jobs:
  typecheck_lint_build:
    name: ⬣, 🔎, 🔨 Typecheck, lint, and build on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    strategy:
      matrix:
        node-version: ["18.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
  publish:
    name: 🚀 Release packages
    needs: [typecheck_lint_build]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    strategy:
      matrix:
        node-version: ["18.x"]
        pnpm-version: ["7.x"]
        os: [ubuntu-latest]
    if: ${{ github.ref == 'refs/heads/master' && (contains(github.event.head_commit.message, '[bump]') || contains(github.event.head_commit.message, 'RELEASING')) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Update npm
        run: npm i -g npm@9
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm
        uses: changesets/action@v1
        with:
          commit: "Publish packages"
          title: "Publish packages"
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
